#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-mdit_py_plugins
Version  : 0.3.1
Release  : 11
URL      : https://files.pythonhosted.org/packages/5f/53/f89a5e343bd9fc1f44efd25b53530d1044e9fe78dc451aca25f75b69df0d/mdit-py-plugins-0.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/5f/53/f89a5e343bd9fc1f44efd25b53530d1044e9fe78dc451aca25f75b69df0d/mdit-py-plugins-0.3.1.tar.gz
Summary  : Collection of plugins for markdown-it-py
Group    : Development/Tools
License  : MIT
Requires: pypi-mdit_py_plugins-license = %{version}-%{release}
Requires: pypi-mdit_py_plugins-python = %{version}-%{release}
Requires: pypi-mdit_py_plugins-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
# mdit-py-plugins
[![Github-CI][github-ci]][github-link]
[![Coverage Status][codecov-badge]][codecov-link]
[![PyPI][pypi-badge]][pypi-link]
[![Conda][conda-badge]][conda-link]
[![Code style: black][black-badge]][black-link]

%package license
Summary: license components for the pypi-mdit_py_plugins package.
Group: Default

%description license
license components for the pypi-mdit_py_plugins package.


%package python
Summary: python components for the pypi-mdit_py_plugins package.
Group: Default
Requires: pypi-mdit_py_plugins-python3 = %{version}-%{release}

%description python
python components for the pypi-mdit_py_plugins package.


%package python3
Summary: python3 components for the pypi-mdit_py_plugins package.
Group: Default
Requires: python3-core
Provides: pypi(mdit_py_plugins)
Requires: pypi(markdown_it_py)

%description python3
python3 components for the pypi-mdit_py_plugins package.


%prep
%setup -q -n mdit-py-plugins-0.3.1
cd %{_builddir}/mdit-py-plugins-0.3.1
pushd ..
cp -a mdit-py-plugins-0.3.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664288785
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . docutils
pypi-dep-fix.py . markdown-it-py
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pypi-dep-fix.py . docutils
pypi-dep-fix.py . markdown-it-py
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins
cp %{_builddir}/mdit-py-plugins-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/ab5a711cce75e49bdbd08bbcb728262e30580e5d || :
cp %{_builddir}/mdit-py-plugins-%{version}/mdit_py_plugins/container/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/69fcf444c57897f60cc8189191798d32ace634f8 || :
cp %{_builddir}/mdit-py-plugins-%{version}/mdit_py_plugins/deflist/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/26e00dbad9e333aeec5c446047d7b5489e2d3c6b || :
cp %{_builddir}/mdit-py-plugins-%{version}/mdit_py_plugins/footnote/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/26e00dbad9e333aeec5c446047d7b5489e2d3c6b || :
cp %{_builddir}/mdit-py-plugins-%{version}/mdit_py_plugins/front_matter/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/752f88468d4c37d8f9d97b8e4031d92bdfe8e501 || :
cp %{_builddir}/mdit-py-plugins-%{version}/mdit_py_plugins/texmath/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/78a8778ee015c0603f4f0a9cd2cfe8c95ce791b0 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
pypi-dep-fix.py %{buildroot} docutils
pypi-dep-fix.py %{buildroot} markdown-it-py
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mdit_py_plugins/26e00dbad9e333aeec5c446047d7b5489e2d3c6b
/usr/share/package-licenses/pypi-mdit_py_plugins/69fcf444c57897f60cc8189191798d32ace634f8
/usr/share/package-licenses/pypi-mdit_py_plugins/752f88468d4c37d8f9d97b8e4031d92bdfe8e501
/usr/share/package-licenses/pypi-mdit_py_plugins/78a8778ee015c0603f4f0a9cd2cfe8c95ce791b0
/usr/share/package-licenses/pypi-mdit_py_plugins/ab5a711cce75e49bdbd08bbcb728262e30580e5d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
