#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v19
# autospec commit: f35655a
#
Name     : pypi-mdit_py_plugins
Version  : 0.4.2
Release  : 24
URL      : https://files.pythonhosted.org/packages/19/03/a2ecab526543b152300717cf232bb4bb8605b6edb946c845016fa9c9c9fd/mdit_py_plugins-0.4.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/19/03/a2ecab526543b152300717cf232bb4bb8605b6edb946c845016fa9c9c9fd/mdit_py_plugins-0.4.2.tar.gz
Summary  : Collection of plugins for markdown-it-py
Group    : Development/Tools
License  : MIT
Requires: pypi-mdit_py_plugins-license = %{version}-%{release}
Requires: pypi-mdit_py_plugins-python = %{version}-%{release}
Requires: pypi-mdit_py_plugins-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(flit_core)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# mdit-py-plugins
[![Github-CI][github-ci]][github-link]
[![Coverage Status][codecov-badge]][codecov-link]
[![PyPI][pypi-badge]][pypi-link]
[![Conda][conda-badge]][conda-link]
[![Code style: black][black-badge]][black-link]

%package license
Summary: license components for the pypi-mdit_py_plugins package.
Group: Default

%description license
license components for the pypi-mdit_py_plugins package.


%package python
Summary: python components for the pypi-mdit_py_plugins package.
Group: Default
Requires: pypi-mdit_py_plugins-python3 = %{version}-%{release}

%description python
python components for the pypi-mdit_py_plugins package.


%package python3
Summary: python3 components for the pypi-mdit_py_plugins package.
Group: Default
Requires: python3-core
Provides: pypi(mdit_py_plugins)
Requires: pypi(markdown_it_py)

%description python3
python3 components for the pypi-mdit_py_plugins package.


%prep
%setup -q -n mdit_py_plugins-0.4.2
cd %{_builddir}/mdit_py_plugins-0.4.2
pushd ..
cp -a mdit_py_plugins-0.4.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1725980222
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . docutils
pypi-dep-fix.py . markdown-it-py
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
pypi-dep-fix.py . docutils
pypi-dep-fix.py . markdown-it-py
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins
cp %{_builddir}/mdit_py_plugins-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/ab5a711cce75e49bdbd08bbcb728262e30580e5d || :
cp %{_builddir}/mdit_py_plugins-%{version}/mdit_py_plugins/admon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/75f4e3a4d938dcaa4d94194e2fc033e4b6dac7b0 || :
cp %{_builddir}/mdit_py_plugins-%{version}/mdit_py_plugins/container/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/69fcf444c57897f60cc8189191798d32ace634f8 || :
cp %{_builddir}/mdit_py_plugins-%{version}/mdit_py_plugins/deflist/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/26e00dbad9e333aeec5c446047d7b5489e2d3c6b || :
cp %{_builddir}/mdit_py_plugins-%{version}/mdit_py_plugins/footnote/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/26e00dbad9e333aeec5c446047d7b5489e2d3c6b || :
cp %{_builddir}/mdit_py_plugins-%{version}/mdit_py_plugins/front_matter/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/752f88468d4c37d8f9d97b8e4031d92bdfe8e501 || :
cp %{_builddir}/mdit_py_plugins-%{version}/mdit_py_plugins/texmath/LICENSE %{buildroot}/usr/share/package-licenses/pypi-mdit_py_plugins/78a8778ee015c0603f4f0a9cd2cfe8c95ce791b0 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
pypi-dep-fix.py %{buildroot} docutils
pypi-dep-fix.py %{buildroot} markdown-it-py
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-mdit_py_plugins/26e00dbad9e333aeec5c446047d7b5489e2d3c6b
/usr/share/package-licenses/pypi-mdit_py_plugins/69fcf444c57897f60cc8189191798d32ace634f8
/usr/share/package-licenses/pypi-mdit_py_plugins/752f88468d4c37d8f9d97b8e4031d92bdfe8e501
/usr/share/package-licenses/pypi-mdit_py_plugins/75f4e3a4d938dcaa4d94194e2fc033e4b6dac7b0
/usr/share/package-licenses/pypi-mdit_py_plugins/78a8778ee015c0603f4f0a9cd2cfe8c95ce791b0
/usr/share/package-licenses/pypi-mdit_py_plugins/ab5a711cce75e49bdbd08bbcb728262e30580e5d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
